import React from "react"
import { Link } from "gatsby"
import styled from "styled-components"

import Layout from "../components/layout"
import SEO from "../components/seo"
import Button from '../components/Button'

const Container = styled.div`
    height: 60vh;
    width: 60%;
    overflow: auto;
    margin: 0 auto;
    @media(max-width: 650px) {
      max-width: 80%;
   }
`

const Title = styled.h1`
  color: #5272ff;
  font-size: 36px;
  text-align: center;
  font-weight: 700;
  @media(max-width: 650px) {
    font-size: 26px;
    }
`
const SubTitle = styled.h3`
  color: #545454;
  font-size: 24px;
  text-align: center;
  font-weight: 600;
  margin-bottom: 10px;
  @media(max-width: 650px) {
    font-size: 20px;
    }
`
const Text = styled.p`
  font-size: 18px;
  color: #5a5a5a;
  letter-spacing: 0.3px;
  @media(max-width: 650px) {
    font-size: 14px;
    }
`
const ImportantText = styled(Text)`
  letter-spacing: 0.8px;
`

const Terms = () => (
  <Layout>
    <Container>
    <SEO title="Terms of Service" />
    <Title>Terms of Use ("Terms")</Title>
    <SubTitle>Effective 8/1/19</SubTitle>
    <ImportantText>PLEASE NOTE THAT YOUR USE OF AND ACCESS TO OUR SERVICES (DEFINED BELOW) ARE SUBJECT TO THE FOLLOWING TERMS: THESE TERMS INCLUDE A CLASS ACTION WAIVER AND RESOLUTION OF DISPUTES BY ARBITRATION INSTEAD OF BY A COURT PROCEEDING. IF YOU DO NOT AGREE TO ALL OF THE FOLLOWING, YOU MAY NOT USE OR ACCESS THE SERVICES IN ANY MANNER.</ImportantText>
    <Text> Welcome to Hoop, an online service owned and operated by Hoop Support Inc. (“Hoop,” “we” and “us). </Text>
    <Text>Our goal is to give customers an independent, secure platform that saves them time, money, and energy by handling customer service processes on their behalf. </Text>
    <Text>Please read on to learn the rules and restrictions that govern your use of our website(s), products, services and applications (the “Services”). If you have any questions, comments, or concerns regarding these terms or the Services, please send a message to us at 415-212-9862 or via mail at P.O. Box 401158 San Francisco, CA 94140.</Text>
    <Text>These Terms of Use (the “Terms”) are a binding contract between you and Hoop. You must agree to and accept all of the Terms, or you don’t have the right to use the Services. Your using the Services in any way means that you agree to all of these Terms, and these Terms will remain in effect while you use the Services. These Terms include the provisions in this document, as well as those in the 
      <Link to="/privacy" style={{color: 'blue'}}>Privacy Policy</Link>.</Text>
    <Text>Please note, there are additional disclosures and policies included in this document.</Text>
    <SubTitle>Changes to Terms</SubTitle>
    <Text>We are constantly trying to improve our Services, so these Terms may need to change along with the Services. We reserve the right to change the Terms at any time, but if we do, we will bring it to your attention by placing a notice on the hoopsupport.com website, by sending you an email, and/or by some other means. We will also update the “Last Updated” date at the top of these Terms. Any changes to the Terms will be effective immediately for new users of the Services and will be effective thirty (30) days after posting notice of such changes on the Services. Hoop may require you to provide consent to the updated Terms in a specified manner before further use of the Services is permitted.</Text>
    <Text>If you don’t agree with the new Terms, you are free to reject them; unfortunately, that means you will no longer be able to use the Services. If you use the Services in any way after a change to the Terms is effective, that means you agree to all of the changes. PLEASE REGULARLY CHECK THE SITE AND/OR APP TO VIEW THE THEN-CURRENT TERMS.</Text>
    <Text>Except for changes by us as described here, no other amendment or modification of these Terms will be effective unless in writing and signed by both you and us.</Text>
    <SubTitle>Privacy</SubTitle>
    <Text>Hoop takes the privacy of its users very seriously. For this reason, we have created a privacy policy that describes our collection, use, and disclosure practices related to any personal information that your provide to us. For the current Hoop Privacy Policy, please click 
      <Link to="/privacy" style={{color: 'blue'}}>here</Link>.</Text>
      <Text>The Children’s Online Privacy Protection Act (“COPPA”) requires that online service providers obtain parental consent before they knowingly collect personally identifiable information online from children who are under 13. We do not knowingly collect or solicit personally identifiable information from children under 13; if you are a child under 13, please do not attempt to register for the Services or send any personal information about yourself to us. If we learn we have collected personal information from a child under 13, we will delete that information as quickly as possible. If you believe that a child under 13 may have provided us personal information, please send a message to us at 415-212-9862.</Text>
    <SubTitle>Services</SubTitle>
    <Text>Via the Services, Hoop will try to resolve issues you have with third party vendors. You can communicate with us about an issue or problem (the "Issue") you are having with your third party vendor or service provider ("Third Party Provider ") via the functionality of the Services and we will work with the Third Party Provider to try to resolve the Issue and communicate the solution to you. By sending us a request to resolve your Issue, you are authorizing us to communicate with the Third Party Provider, and to try to resolve the Issue on your behalf. In order to use the Services, you'll need to provide us with some personal information, as described in our Privacy Policy. In addition, you'll provide us with information related to the Issue upon our request (e.g. the confirmation number of the transaction you need help with or a copy of the email confirmation from the Third Party Provider). We reserve the right to accept or decline your request to solve an Issue at any stage, in our sole discretion, and will communicate our decision in this regard to you within a reasonable timeframe.</Text>
    <Text>You may be required to sign up for an account, and select a password and user name (“Company User ID”). You promise to provide us with accurate, complete, and updated registration information about yourself. You may not select as your Company User ID a name that you don’t have the right to use, or another person’s name with the intent to impersonate that person. You may not transfer your account to anyone else without our prior written permission.</Text>
    <Text>You represent and warrant that you are an individual of legal age to form a binding contract (or if not, you’ve received your parent’s or guardian’s permission to use the Services and gotten your parent or guardian to agree to these Terms on your behalf).</Text>
    <Text>You will only use the Services for your own internal, personal, non-commercial use, and not on behalf of or for the benefit of any third party, and only in a manner that complies with all laws that apply to you. If your use of the Services is prohibited by applicable laws, then you aren’t authorized to use the Services. We can’t and won’t be responsible for your using the Services in a way that breaks the law.</Text>
    <Text>You will not share your account or password with anyone, and you must protect the security of your account and your password. You’re responsible for any activity associated with your account.</Text>
    <SubTitle>Rights you grant us</SubTitle>
    <Text>During the registration process, you will be asked to enter your user credentials for your online accounts, such as your order number, cable provider, mobile service carrier, or internet service provider (“User Credentials”). Your credentials are used to provide us access to review financial transaction information or other account information for your accounts with these third party providers (each, a “Third Party Provider” and such account information your “Account Information”). You can read more about how we use and store your information in our Privacy Policy and Data Security Policy You hereby authorize and permit us to use the User Credentials submitted by you to perform the Services.</Text>
    <Text>We use your User Credentials to review your Account Information and perform various services on your behalf. For example, we use your Account Information to identify shipping delays, cancel unwanted subscriptions, and negotiate discounts on your bills on your behalf. You expressly authorize us to access, view and use, on your behalf as your agent, your Account Information. </Text>
    <Text>You hereby grant Hoop a limited power of attorney and appoint Hoop as your attorney-in-fact and agent to resolve Issues on your behalf, and use your Account Information provided through the Services with the full power and authority to do and perform each thing necessary in connection with such activities, with the same legal force and effect as if done by you but only to act for and on your behalf with Third Party Providers.</Text>
    <Text>YOU ACKNOWLEDGE AND AGREE THAT WHEN WE ARE ACCESSING YOUR USER CREDENTIALS AND ACCOUNT INFORMATION, WE ARE ACTING AS YOUR AGENT, AND NOT AS THE AGENT OF OR ON BEHALF OF A THIRD PARTY. You understand and agree that Hoop is not sponsored or endorsed by any third parties accessible through the Services.</Text>
    <SubTitle>Additional Restrictions</SubTitle>
    <Text>You represent, warrant, and agree that you will not contribute any Content or User Submission (each of those terms is defined below) or otherwise use the Services or interact with the Services in a manner that:</Text>
    <ul>
      <li>Infringes or violates the intellectual property rights or any other rights of anyone else (including Hoop);</li>
      <li>Violates any law or regulation, including any applicable export control laws;</li>
      <li>Is harmful, fraudulent, deceptive, threatening, harassing, defamatory, obscene, or otherwise objectionable;</li>
      <li>Jeopardizes the security of your Hoop account or anyone else’s (such as allowing someone else to log in to the Services as you);</li>
      <li>Attempts, in any manner, to obtain the password, account, or other security information from any other user;</li>
      <li>Violates the security of any computer network, or cracks any passwords or security encryption codes;</li>
      <li>Runs Maillist, Listserv, any form of auto-responder or “spam” on the Services, or any processes that run or are activated while you are not logged into the Services, or that otherwise interfere with the proper working of the Services (including by placing an unreasonable load on the Services’ infrastructure);</li>
      <li>“Crawls,” “scrapes,” or “spiders” any page, data, or portion of or relating to the Services or Content (through use of manual or automated means);</li>
      <li>Copies or stores any significant portion of the Content;</li>
      <li>Decompiles, reverse engineers, or otherwise attempts to obtain the source code or underlying ideas or information of or relating to the Services.</li>
    </ul>
    <Text>A violation of any of the foregoing is grounds for termination of your right to use or access the Services.</Text>
    <Text>You must provide all equipment and software necessary to connect to the Services, including but not limited to, a mobile device that is suitable to connect with and use the Services, in cases where the Services offer a mobile component. You are solely responsible for any fees, including Internet connection or mobile fees, that you incur when accessing the Services.</Text>
    <SubTitle>Eligibility</SubTitle>
    <Text>You may use the Services only if you are 18 years or older and are not barred from using the Services under applicable law. Currently, we only offer the Services to customers in the United States.</Text>
  <SubTitle>Rights</SubTitle>
  <Text>The materials displayed or performed or available on or through the Services, including, but not limited to, text, graphics, data, articles, photos, images, illustrations, User Submissions, and so forth (all of the foregoing, the “Content”) are protected by copyright and/or other intellectual property laws. You promise to abide by all copyright notices, trademark rules, information, and restrictions contained in any Content you access through the Services, and you won’t use, copy, reproduce, modify, translate, publish, broadcast, transmit, distribute, perform, upload, display, license, sell or otherwise exploit for any purpose any Content not owned by you, (i) without the prior consent of the owner of that Content or (ii) in a way that violates someone else’s (including Hoop’s) rights.</Text>
    <Text>You understand that Hoop owns the Services. You won’t modify, publish, transmit, participate in the transfer or sale of, reproduce (except as expressly provided in this Section), create derivative works based on, or otherwise exploit any of the Services.</Text>
    <Text>The Services may allow you to copy or download certain Content; please remember that just because this functionality exists, doesn’t mean that all the restrictions above don’t apply – they do!</Text>
    <SubTitle>Content and Content Rights</SubTitle>
    <Text>In the course of using the Services, you and other users may provide information (other than Financial Credentials and Transaction Information), such as posts and comments on our website, which may be used by us in connection with the Services and which may be visible to certain other users. You understand that by posting information or content on the Services or otherwise providing content, materials or information to us or in connection with the Services (collectively, “User Submissions”), you hereby grant Hoop a non-exclusive, worldwide, royalty-free, perpetual, irrevocable, sublicenseable and transferable license to use such User Submissions (including all related intellectual property rights) in connection with the Services and our business, including without limitation for promoting and redistributing part or all of the Services (and derivative works thereof) in any media formats and through any media channels. This is a license only – your ownership in User Submissions is not affected.</Text>
    <Text>You also agree that if your User Submissions contains any feedback, ideas, concepts, or techniques, we can use the User Submissions and anything it contains for any purpose including, but not limited to, developing, manufacturing and marketing services. Please note that the foregoing licenses are subject to our Privacy Policy to the extent they relate to User Submissions that are also your personally-identifiable information.</Text>
    <SubTitle>Content Ownership, Responsibility and Removal </SubTitle>
    <Text>Any information or content publicly posted or privately transmitted through the Services is the sole responsibility of the person from whom such content originated, and you access all such information and content at your own risk, and we aren’t liable for any errors or omissions in that information or content or for any damages or loss you might suffer in connection with it. We cannot control and have no duty to take any action regarding how you may interpret and use the Content or what actions you may take as a result of having been exposed to the Content, and you hereby release us from all liability for you having acquired or not acquired Content through the Services. We can’t guarantee the identity of any users with whom you interact in using the Services and are not responsible for which users gain access to the Services.</Text>
    <Text>You are responsible for all Content you contribute, in any manner, to the Services, and you represent and warrant you have all rights necessary to do so, in the manner in which you contribute it. You will keep all your registration information accurate and current. You are responsible for all your activity in connection with the Services.</Text>
    <Text>The Services may contain links or connections to third party websites or services that are not owned or controlled by Hoop. When you access third party websites or use third party services, you accept that there are risks in doing so, and that Hoop is not responsible for such risks. We encourage you to be aware when you leave the Services and to read the terms and conditions and privacy policy of each third party website or service that you visit or utilize.</Text>
    <Text>Hoop has no control over, and assumes no responsibility for, the content, accuracy, privacy policies, or practices of or opinions expressed in any third party websites or by any third party that you interact with through the Services. In addition, Hoop will not and cannot monitor, verify, censor or edit the content of any third party site or service. By using the Services, you release and hold us harmless from any and all liability arising from your use of any third party website or service.</Text>
    <Text>Your interactions with organizations and/or individuals found on or through the Services, including payment and delivery of goods or services, and any other terms, conditions, warranties or representations associated with such dealings, are solely between you and such organizations and/or individuals. You should make whatever investigation you feel necessary or appropriate before proceeding with any online or offline transaction with any of these third parties. You agree that Hoop shall not be responsible or liable for any loss or damage of any sort incurred as the result of any such dealings.</Text>
    <Text>If there is a dispute between participants on this site, or between users and any third party, you agree that Hoop is under no obligation to become involved. In the event that you have a dispute with one or more other users, you release Hoop, its officers, employees, agents, and successors from claims, demands, and damages of every kind or nature, known or unknown, suspected or unsuspected, disclosed or undisclosed, arising out of or in any way related to such disputes and/or our Services. If you are a California resident, you shall and hereby do waive California Civil Code Section 1542, which says: "A general release does not extend to claims which the creditor does not know or suspect to exist in his or her favor at the time of executing the release, which, if known by him or her must have materially affected his or her settlement with the debtor."</Text>
    <SubTitle>Copyright Infringement</SubTitle>
    <Text>You may have heard of the Digital Millennium Copyright Act (the “DMCA”), as it relates to online service providers, like Hoop, being asked to remove material that allegedly violates someone’s copyright. We respect others’ intellectual property rights, and we reserve the right to delete or disable Content alleged to be infringing, and to terminate the accounts of repeat alleged infringers. To learn more about the DMCA, click 
      <a href="https://www.dmca.com/" style={{color: 'blue'}} target="blank">here</a>.</Text>
      <SubTitle>Changes to Services</SubTitle>
      <Text>We’re always trying to improve the Services, so they may change over time. We may suspend or discontinue any part of the Services, or we may introduce new features or impose limits on certain features or restrict access to parts or all of the Services. We’ll try to give you notice when we make a material change to the Services that would adversely affect you, but this isn’t always practical. Similarly, we reserve the right to remove any Content from the Services at any time, for any reason (including, but not limited to, if someone alleges you contributed that Content in violation of these Terms), in our sole discretion, and without notice.</Text>
    <SubTitle>Payment</SubTitle>
    <Text>Hoop charges a fixed fee to resolve each Issue. In exchange for using our Services, you agree to pay all fees or charges to your Account in accordance with the fees, charges and billing terms in effect at the time a fee or charge is due and payable. You must provide Company with a valid credit card (Visa, MasterCard, or any other issuer accepted by us) (“Payment Provider”) as a condition to signing up for the Services. Your Payment Provider agreement governs your use of the designated credit card, and you must refer to that agreement and not the Terms to determine your rights and liabilities. By providing us with your credit card number and associated payment information, you agree that we are authorized to immediately invoice your Account for all fees and charges due and payable to us hereunder and that no additional notice or consent is required. You agree to immediately notify us of any change in your billing address or the credit card used for payment. We reserve the right at any time to change our prices and billing methods, either immediately upon posting on our Services or by e-mail delivery to you.</Text>
    <Text>We use PayPal as the third party service provider for payment services (e.g., card acceptance, merchant settlement, and related services). By paying for the Services, you agree to be bound by PayPal’s Privacy Policy and hereby consent and authorize us and PayPal to share any information and payment instructions you provide with Third Party Service Provider(s) to the minimum extent required to complete your transactions. YOU AUTHORIZE HOOP OR PAYPAL TO CHARGE YOUR CREDIT CARD OR OTHER FORM OF PAYMENT YOU PROVIDE TO US FOR THE FEES AS DESCRIBED ABOVE.</Text>
    <Text>We reserve the right to charge for certain or all Services in the future. We will notify you before any Services you are then using begin carrying a fee, and if you wish to continue using such Services, you must pay all applicable fees for such Services.</Text>
    <SubTitle>Termination</SubTitle>
    <Text>You’re free to do that at any time, by sending a message to us at 415-212-9862; please refer to our Privacy Policy as well as the licenses above, to understand how we treat information you provide to us after you have stopped using our Services.</Text>
    <Text>Hoop is also free to terminate (or suspend access to) your use of the Services or your account, for any reason in our discretion, including your breach of these Terms. Hoop has the sole right to decide whether you are in violation of any of the restrictions set forth in these Terms.</Text>
    <Text>Account termination may result in destruction of any Content associated with your account, so keep that in mind before you decide to terminate your account.</Text>
    <Text>Provisions that, by their nature, should survive termination of these Terms shall survive termination. By way of example, all of the following will survive termination: any obligation you have to pay us or indemnify us, any limitations on our liability, any terms regarding ownership or intellectual property rights, and terms regarding disputes between us.</Text>
    <SubTitle>Warranty Disclaimer</SubTitle>
    <Text>Neither Hoop nor its licensors or suppliers makes any representations or warranties concerning any content contained in or accessed through the Services, and we will not be responsible or liable for the accuracy, copyright compliance, legality, or decency of material contained in or accessed through the Services. We (and our licensors and suppliers) make no representations or warranties regarding suggestions or recommendations of services or products offered or purchased through the Services. Products and services purchased or offered (whether or not following such recommendations and suggestions) through the Services are provided “AS IS” and without any warranty of any kind from Company or others (unless, with respect to such others only, provided expressly and unambiguously in writing by a designated third party for a specific product). </Text>
    <Text>THE SERVICES AND CONTENT ARE PROVIDED BY HOOP (AND ITS LICENSORS AND SUPPLIERS) ON AN “AS-IS” BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING, WITHOUT LIMITATION, IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, OR THAT USE OF THE SERVICES WILL BE UNINTERRUPTED OR ERROR-FREE. WE MAKE NO GUARANTEE ABOUT THE RESULTS THAT MAY BE OBTAINED FROM YOUR USE OF THE SERVICES, INCLUDING WITHOUT LIMITATION ANY GUARANTEE ABOUT THE AMOUNT OF MONEY YOU MAY SAVE. SOME STATES DO NOT ALLOW LIMITATIONS ON HOW LONG AN IMPLIED WARRANTY LASTS, SO THE ABOVE LIMITATIONS MAY NOT APPLY TO YOU.</Text>
    <Text>Limitation of Liability.</Text>
    <Text>TO THE FULLEST EXTENT ALLOWED BY APPLICABLE LAW, UNDER NO CIRCUMSTANCES AND UNDER NO LEGAL THEORY (INCLUDING, WITHOUT LIMITATION, TORT, CONTRACT, STRICT LIABILITY, OR OTHERWISE) SHALL HOOP (OR ITS LICENSORS OR SUPPLIERS) BE LIABLE TO YOU OR TO ANY OTHER PERSON FOR (A) ANY INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES OF ANY KIND, INCLUDING DAMAGES FOR LOST PROFITS, LOSS OF GOODWILL, WORK STOPPAGE, ACCURACY OF RESULTS, OR COMPUTER FAILURE OR MALFUNCTION, OR (B) ANY AMOUNT, IN THE AGGREGATE, IN EXCESS OF THE GREATER OF (I) $50 OR (II) THE AMOUNTS PAID BY YOU TO COMPANY IN CONNECTION WITH THE SERVICES IN THE TWELVE (12) MONTH PERIOD PRECEDING THIS APPLICABLE CLAIM, OR (C) ANY MATTER BEYOND OUR REASONABLE CONTROL. SOME STATES DO NOT ALLOW THE EXCLUSION OR LIMITATION OF CERTAIN DAMAGES, SO THE ABOVE LIMITATION AND EXCLUSIONS MAY NOT APPLY TO YOU.</Text>
    <Text>Indemnity.</Text>
    <Text>You agree to indemnify and hold Hoop, its affiliates, officers, agents, employees, and partners harmless from and against any and all claims, liabilities, damages (actual and consequential), losses and expenses (including attorneys’ fees) arising from or in any way related to any third party claims relating to (a) your use of the Services (including any actions taken by a third party using your account), and (b) your violation of these Terms. In the event of such a claim, suit, or action (“Claim”), we will attempt to provide notice of the Claim to the contact information we have for your account (provided that failure to deliver such notice shall not eliminate or reduce your indemnification obligations hereunder).</Text>
    <Text>Assignment.</Text>
    <Text>You may not assign, delegate or transfer these Terms or your rights or obligations hereunder, or your Services account, in any way (by operation of law or otherwise) without Hoop’s prior written consent. We may transfer, assign, or delegate these Terms and our rights and obligations without consent.</Text>
    <Text>Choice of Law; Arbitration.</Text>
    <Text>These Terms are governed by and will be construed under the laws of the State of California, without regard to the conflicts of laws provisions thereof. Any dispute arising from or relating to the subject matter of these Terms shall be finally settled in San Francisco County, California, in English, in accordance with the Streamlined Arbitration Rules and Procedures of Judicial Arbitration and Mediation Services, Inc. ("JAMS") then in effect, by one commercial arbitrator with substantial experience in resolving intellectual property and commercial contract disputes, who shall be selected from the appropriate list of JAMS arbitrators in accordance with such Rules. Judgment upon the award rendered by such arbitrator may be entered in any court of competent jurisdiction. Notwithstanding the foregoing obligation to arbitrate disputes, each party shall have the right to pursue injunctive or other equitable relief at any time, from any court of competent jurisdiction. For all purposes of these Terms, the parties consent to exclusive jurisdiction and venue in the state or federal courts located in, respectively, San Francisco County, California, or the Northern District of California. Any arbitration under these Terms will take place on an individual basis: class arbitrations and class actions are not permitted. YOU UNDERSTAND AND AGREE THAT BY ENTERING INTO THESE TERMS, YOU AND COMPANY ARE EACH WAIVING THE RIGHT TO TRIAL BY JURY OR TO PARTICIPATE IN A CLASS ACTION.</Text>
    <Text>Miscellaneous.</Text>
    <Text>You will be responsible for paying, withholding, filing, and reporting all taxes, duties, and other governmental assessments associated with your activity in connection with the Services, provided that the Company may, in its sole discretion, do any of the foregoing on your behalf or for itself as it sees fit. The failure of either you or us to exercise, in any way, any right herein shall not be deemed a waiver of any further rights hereunder. If any provision of these Terms is found to be unenforceable or invalid, that provision will be limited or eliminated, to the minimum extent necessary, so that these Terms shall otherwise remain in full force and effect and enforceable. You and Hoop agree that these Terms are the complete and exclusive statement of the mutual understanding between you and Hoop, and that it supersedes and cancels all previous written and oral agreements, communications and other understandings relating to the subject matter of these Terms. You hereby acknowledge and agree that you are not an employee, agent, partner, or joint venture of Hoop, and you do not have any authority of any kind to bind Hoop in any respect whatsoever. You and Hoop agree there are no third party beneficiaries intended under these Terms.</Text>
    <Text>General Terms</Text>
    <Text>These Terms constitute the entire and exclusive understanding and agreement between Hoop and you regarding the Services, and these Terms supersede any and all prior oral or written understandings or agreements between Service and you regarding the Services. If for any reason a court of competent jurisdiction finds any provision of these Terms invalid or unenforceable, that provision will be enforced to the maximum extent permissible and the other provisions of these Terms will remain in full force and effect.</Text>
    <Text>Any waiver or failure to enforce any provision of the Terms on one occasion will not be deemed a waiver of any other provision or of such provision on any other occasion.</Text>
    <Text>If any provision of the Terms is, for any reason, held to be invalid or unenforceable, the other provisions of the Terms will remain enforceable, and the invalid or unenforceable provision will be deemed modified so that it is valid and enforceable to the maximum extent permitted by law.</Text>
    <Text>We can freely assign or transfer these Terms without restriction; the Terms will bind and inure to the benefit of the parties, their successors and permitted assigns. The Terms, and your rights and obligations hereunder, may not be assigned, subcontracted, delegated, or otherwise transferred by you without Hoop’s prior written consent, and any attempted assignment, subcontract, delegation or transfer in violation of the foregoing will be null and void.</Text>
    <Text>You hereby release Hoop and its successors from claims, demands, any and all losses, damages, rights, and actions of any kind, including personal injuries, death, and property damage, that is either directly or indirectly related to or arises from your use of the Services, including but not limited to, any interactions with or conduct of other users or third-party websites (including Vendors) of any kind arising in connection with or as a result of the Terms or your use of the Services. If you are a California resident, you hereby waive California Civil Code Section 1542, which states, “A general release does not extend to claims which the creditor does not know or suspect to exist in his favor at the time of executing the release, which, if known by him must have materially affected his settlement with the debtor.</Text>
    <Text>Any notices or other communications provided by us under these Terms, including those regarding modifications to these Terms, will be given: (i) via email; or (ii) by posting to the Services. For notices made by e-mail, the date of receipt will be deemed the date on which such notice is transmitted.</Text>
    <Text>Service's failure to enforce any right or provision of these Terms will not be considered a waiver of such right or provision. Except as expressly set forth in these Terms, the exercise by either party of any of its remedies under these Terms will be without prejudice to its other remedies under these Terms or otherwise.</Text>
    <SubTitle>Contact Information</SubTitle>
    <Text>If you have any questions about these Terms or the Services, please send a message to Hoop at 415-212-9862.</Text>
    {/* <Link to="/">Go back to the homepage</Link> */}
    </Container>
    <Button />
  </Layout>
)

export default Terms
